# integer类型的attribute，先确定取值范围再确定具体数值
# 变量分布可以和至多一个cate类别的attr相关

type: integer

depend: state

initial:
    GOLD1:
        18: 0.1
        30: 0.3
        50: 0.3
        70: 0.3
        90: 0.0
    GOLD2:
        18: 0.1
        30: 0.3
        50: 0.3
        70: 0.3
        90: 0.0
    GOLD3:
        18: 0.1
        30: 0.3
        50: 0.3
        70: 0.3
        90: 0.0
    GOLD4:
        18: 0.1
        30: 0.3
        50: 0.3
        70: 0.3
        90: 0.0

incidence:
    GOLD1:
        18: 0.1
        30: 0.3
        50: 0.3
        70: 0.3
        90: 0.0
    GOLD2:
        18: 0.1
        30: 0.3
        50: 0.3
        70: 0.3
        90: 0.0
    GOLD3:
        18: 0.1
        30: 0.3
        50: 0.3
        70: 0.3
        90: 0.0
    GOLD4:
        18: 0.1
        30: 0.3
        50: 0.3
        70: 0.3
        90: 0.0